# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32bf24d879db0488eeb8290964176afc24460ca2bc1aaf624ac2fe3150cf9a615369e61513aef19aca8f119facf7a09e2988ccce7c71942963995eb4b42a81d1

test:
  secret_key_base: a8a697af12da1d64dc66f14d5c6087826100199534ea49a39da85734cf3959f53e5c37b233f422ff0b3939889dc456618725b124a402439397d27264def9493c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
